# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f209e751e93897035a19a9ff868c8fa0b5b388a98fd1658deb5554a25f2f31381927379ce2a9ce76509d7f9b86a50d7afa60274eeea751200cc6c0adc3a23d14

test:
  secret_key_base: 4be5d4c9c340f91a155c75067a992073806a540627a0ede1f3376123f55d48e6f7f987e7835c3118cf25f01d3e869c4ed61deed7603f29dbd58dea6c9fa82d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
